version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: sgpic_development

  web:
    build: .
    environment:
      - ENCRYPTION_KEY=ojfQdKH7AkwoQDmUCDsGvnV0riP+5NXS6oCBxBqiwCY=
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/sgpic"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
