default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user
  password: password
  host: localhost

development:
  <<: *default
  database: sgpic_development

test:
  <<: *default
  database: sgpic_test

production:
#  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: sgpic_production
  username: sgpic
  password: Senhasgpic123#
  host: localhost
  port: 5432
