default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user
  password: password
  host: db

development:
  <<: *default
  database: sgpic_development

test:
  <<: *default
  database: sgpic_test

production:
  <<: *default
  database: sgpic_production
  username: sgpic
  password: <%= ENV['SGPIC_DATABASE_PASSWORD'] %>
