name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sgpic_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d sgpic_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup system dependencies
        run: sudo apt-get update && sudo apt-get install -y tar gzip xz-utils nodejs postgresql-client

      - name: Install Bundler
        run: gem install bundler --user-install

      - name: Configure PATH for Bundler
        run: echo "PATH=$HOME/.local/share/gem/ruby/3.0.0/bin:\$PATH" >> $GITHUB_ENV

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install gems
        run: |
          bundle install --jobs=4 --retry=3

      - name: Prepare database
        run: |
          cp config/database.yml config/database.yml.ci
          sed -i 's/sgpic_development/sgpic_test/g' config/database.yml.ci
          RAILS_ENV=test rails db:create db:schema:load

      - name: Run tests
        run: |
          RAILS_ENV=test bundle exec rspec
