name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgresql://user:password@localhost:5432/sgpic_test"
      ENCRYPTION_KEY: ojfQdKH7AkwoQDmUCDsGvnV0riP+5NXS6oCBxBqiwCY=

    services:
      db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: sgpic_test
        options: >-
          --health-cmd="pg_isready -U user -d sgpic_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Install dependencies
        run: |
          gem install bundler:2.4.21
          bundle check || bundle install --jobs=4 --retry=3

      - name: Set up database
        run: |
          bin/rails db:drop || true
          bin/rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec --format documentation
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-135-198-225.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-135-198-225.us-east-2.compute.amazonaws.com << 'EOF'
            cd /ubuntu/home/sgpic
            git pull origin main
            RAILS_ENV=production bundle install --deployment --without development test
            RAILS_ENV=production bin/rails db:migrate
            RAILS_ENV=production bin/rails assets:precompile
            sudo systemctl restart rails-app
          EOF